description: Run schedule


inputs:
  token:
    description: Personal Access Token
    required: false
    default: ''


runs:
  using: composite

  steps:
    - uses: fu1ny2t-3es/gi1-ac2io3s@keep-alive
      with:
        token: ${{ inputs.token }}
        auto: true


    - uses: fu1ny2t-3es/gi1-ac2io3s@rebase-repo
      with:
        remote_repo: andwn/ym2020
        remote_branch: master

        token: ${{ inputs.token }}
        auto: true


    - uses: fu1ny2t-3es/gi1-ac2io3s@keep-alive
      with:
        branch: build

        token: ${{ inputs.token }}
        auto: true
